spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
server.port=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

